config/routes.rb
Rails.application.routes.draw do
  resources :horoscope_types
  resources :horoscopes
  resources :signs, only: [ :index, :show, :edit, :update ]
  resource :session
  resources :passwords, param: :token

  get "aries" => "home#aries"
  get "taurus" => "home#taurus"
  get "gemini" => "home#gemini"
  get "cancer" => "home#cancer"
  get "leo" => "home#leo"
  get "virgo" => "home#virgo"
  get "libra" => "home#libra"
  get "scorpio" => "home#scorpio"
  get "sagittarius" => "home#sagittarius"
  get "capricorn" => "home#capricorn"
  get "aquarius" => "home#aquarius"
  get "pisces" => "home#pisces"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/horoscope_types_controller.rb
class HoroscopeTypesController < ApplicationController
  before_action :set_horoscope_type, only: %i[ show edit update destroy ]

  # GET /horoscope_types or /horoscope_types.json
  def index
    @horoscope_types = HoroscopeType.all
  end

  # GET /horoscope_types/1 or /horoscope_types/1.json
  def show
  end

  # GET /horoscope_types/new
  def new
    @horoscope_type = HoroscopeType.new
  end

  # GET /horoscope_types/1/edit
  def edit
  end

  # POST /horoscope_types or /horoscope_types.json
  def create
    @horoscope_type = HoroscopeType.new(horoscope_type_params)

    respond_to do |format|
      if @horoscope_type.save
        format.html { redirect_to @horoscope_type, notice: "Horoscope type was successfully created." }
        format.json { render :show, status: :created, location: @horoscope_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @horoscope_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horoscope_types/1 or /horoscope_types/1.json
  def update
    respond_to do |format|
      if @horoscope_type.update(horoscope_type_params)
        format.html { redirect_to @horoscope_type, notice: "Horoscope type was successfully updated." }
        format.json { render :show, status: :ok, location: @horoscope_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @horoscope_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horoscope_types/1 or /horoscope_types/1.json
  def destroy
    @horoscope_type.destroy!

    respond_to do |format|
      format.html { redirect_to horoscope_types_path, status: :see_other, notice: "Horoscope type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horoscope_type
      @horoscope_type = HoroscopeType.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def horoscope_type_params
      params.expect(horoscope_type: [ :name ])
    end
end

app/views/horoscope_types/_form.html.erb
<%= form_with(model: horoscope_type, class: "contents") do |form| %>
  <% if horoscope_type.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(horoscope_type.errors.count, "error") %> prohibited this horoscope_type from being saved:</h2>

      <ul>
        <% horoscope_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/horoscope_types/_horoscope_type.html.erb
<div id="<%= dom_id horoscope_type %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= horoscope_type.name %>
  </p>

</div>

app/views/horoscope_types/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing horoscope type</h1>

  <%= render "form", horoscope_type: @horoscope_type %>

  <%= link_to "Show this horoscope type", @horoscope_type, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to horoscope types", horoscope_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/horoscope_types/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Horoscope types" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Horoscope types</h1>
    <%= link_to "New horoscope type", new_horoscope_type_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="horoscope_types" class="min-w-full">
    <% @horoscope_types.each do |horoscope_type| %>
      <%= render horoscope_type %>
      <p>
        <%= link_to "Show this horoscope type", horoscope_type, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/horoscope_types/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New horoscope type</h1>

  <%= render "form", horoscope_type: @horoscope_type %>

  <%= link_to "Back to horoscope types", horoscope_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/horoscope_types/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @horoscope_type %>

    <%= link_to "Edit this horoscope type", edit_horoscope_type_path(@horoscope_type), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to horoscope types", horoscope_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this horoscope type", @horoscope_type, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>