config/routes.rb
Rails.application.routes.draw do
  resources :horoscope_types
  resources :horoscopes
  resources :signs, only: [ :index, :show, :edit, :update ]
  resource :session
  resources :passwords, param: :token

  get "aries" => "home#aries"
  get "taurus" => "home#taurus"
  get "gemini" => "home#gemini"
  get "cancer" => "home#cancer"
  get "leo" => "home#leo"
  get "virgo" => "home#virgo"
  get "libra" => "home#libra"
  get "scorpio" => "home#scorpio"
  get "sagittarius" => "home#sagittarius"
  get "capricorn" => "home#capricorn"
  get "aquarius" => "home#aquarius"
  get "pisces" => "home#pisces"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/sign.rb
class Sign < ApplicationRecord
  has_many :signs, dependent: :destroy
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  before_action :set_sign, only: %i[ show edit update ]

  # GET /signs or /signs.json
  def index
    @signs = Sign.all
  end

  # GET /signs/1 or /signs/1.json
  def show
  end

  # GET /signs/1/edit
  def edit
  end

  # PATCH/PUT /signs/1 or /signs/1.json
  def update
    respond_to do |format|
      if @sign.update(sign_params)
        format.html { redirect_to @sign, notice: "Sign was successfully updated." }
        format.json { render :show, status: :ok, location: @sign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sign.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign
      @sign = Sign.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def sign_params
      params.expect(sign: [ :description, :period ])
    end
end

app/views/signs/_form.html.erb
<%= form_with(model: sign, class: "contents") do |form| %>
  <% if sign.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(sign.errors.count, "error") %> prohibited this sign from being saved:</h2>

      <ul>
        <% sign.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :period %>
    <%= form.text_field :period, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/signs/_sign.html.erb
<div id="<%= dom_id sign %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= sign.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= sign.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Period:</strong>
    <%= sign.period %>
  </p>

</div>

app/views/signs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing sign</h1>

  <%= render "form", sign: @sign %>

  <%= link_to "Show this sign", @sign, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to signs", signs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/signs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Signs" %>

  <div class="flex justify-between items-center my-4">
    <h1 class="font-bold text-4xl">Signs</h1>
  </div>

  <div id="signs" class="my-4">
    <table class="min-w-full">
      <thead>
        <tr>
          <th class="py-2">Name</th>
          <th class="py-2">Period</th>
          <th class="py-2"></th>
        </tr>
      </thead>
      <tbody>
        <% @signs.each do |sign| %>
          <tr>
            <td class="border px-2 py-2"><%= sign.name %></td>
            <td class="border px-2 py-2"><%= sign.period %></td>
            <td class="border px-2 py-2">
              <%= link_to "Show", sign, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
              <%= link_to "Edit", edit_sign_path(sign), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/signs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @sign %>

    <%= link_to "Edit this sign", edit_sign_path(@sign), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>