config/routes.rb
Rails.application.routes.draw do
  resources :horoscope_types
  resources :horoscopes
  resources :signs, only: [ :index, :show, :edit, :update ]
  resource :session
  resources :passwords, param: :token

  get "aries" => "home#aries"
  get "taurus" => "home#taurus"
  get "gemini" => "home#gemini"
  get "cancer" => "home#cancer"
  get "leo" => "home#leo"
  get "virgo" => "home#virgo"
  get "libra" => "home#libra"
  get "scorpio" => "home#scorpio"
  get "sagittarius" => "home#sagittarius"
  get "capricorn" => "home#capricorn"
  get "aquarius" => "home#aquarius"
  get "pisces" => "home#pisces"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/horoscope.rb
class Horoscope < ApplicationRecord
  belongs_to :sign

  has_rich_text :body
end

app/models/horoscope_type.rb
class HoroscopeType < ApplicationRecord
end

app/controllers/horoscopes_controller.rb
class HoroscopesController < ApplicationController
  before_action :set_horoscope, only: %i[ show edit update destroy ]

  # GET /horoscopes or /horoscopes.json
  def index
    @horoscopes = Horoscope.page params[:page]
  end

  # GET /horoscopes/1 or /horoscopes/1.json
  def show
  end

  # GET /horoscopes/new
  def new
    @horoscope = Horoscope.new
  end

  # GET /horoscopes/1/edit
  def edit
  end

  # POST /horoscopes or /horoscopes.json
  def create
    @horoscope = Horoscope.new(horoscope_params)

    respond_to do |format|
      if @horoscope.save
        format.html { redirect_to @horoscope, notice: "Horoscope was successfully created." }
        format.json { render :show, status: :created, location: @horoscope }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @horoscope.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horoscopes/1 or /horoscopes/1.json
  def update
    respond_to do |format|
      if @horoscope.update(horoscope_params)
        format.html { redirect_to @horoscope, notice: "Horoscope was successfully updated." }
        format.json { render :show, status: :ok, location: @horoscope }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @horoscope.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horoscopes/1 or /horoscopes/1.json
  def destroy
    @horoscope.destroy!

    respond_to do |format|
      format.html { redirect_to horoscopes_path, status: :see_other, notice: "Horoscope was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horoscope
      @horoscope = Horoscope.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def horoscope_params
      params.expect(horoscope: [ :title, :body, :sign_id, :start_date, :end_date ])
    end
end

app/helpers/horoscopes_helper.rb
module HoroscopesHelper
end

app/views/horoscopes/_form.html.erb
<%= form_with(model: horoscope, class: "contents") do |form| %>
  <% if horoscope.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(horoscope.errors.count, "error") %> prohibited this horoscope from being saved:</h2>

      <ul>
        <% horoscope.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.rich_textarea :body %>
  </div>

  <div class="my-5">
    <%= form.label :sign_id %>
    <%= form.text_field :sign_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/horoscopes/_horoscope.html.erb
<div id="<%= dom_id horoscope %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= horoscope.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= horoscope.body %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Sign:</strong>
    <%= horoscope.sign_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start date:</strong>
    <%= horoscope.start_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End date:</strong>
    <%= horoscope.end_date %>
  </p>

</div>

app/views/horoscopes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing horoscope</h1>

  <%= render "form", horoscope: @horoscope %>

  <%= link_to "Show this horoscope", @horoscope, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to horoscopes", horoscopes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/horoscopes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Horoscopes" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Horoscopes</h1>
    <%= link_to "New horoscope", new_horoscope_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="horoscopes" class="min-w-full">
    <% @horoscopes.each do |horoscope| %>
      <%= render horoscope %>
      <p>
        <%= link_to "Show this horoscope", horoscope, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
    <%= paginate @horoscopes %>
  </div>
</div>

app/views/horoscopes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New horoscope</h1>

  <%= render "form", horoscope: @horoscope %>

  <%= link_to "Back to horoscopes", horoscopes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/horoscopes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @horoscope %>

    <%= link_to "Edit this horoscope", edit_horoscope_path(@horoscope), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to horoscopes", horoscopes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this horoscope", @horoscope, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>